ALTER TABLE customers
    ADD COLUMN IF NOT EXISTS tax_id VARCHAR(128) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS document_url TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS document_path VARCHAR(512) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS document_mime_type VARCHAR(128) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS document_file_name VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS document_size BIGINT UNSIGNED DEFAULT NULL;
