export const state = {
  afterSubmitCallback: null,
  cachedProjects: [],
  customerOptionMap: new Map(),
  customerEntries: [],
  projectOptionMap: new Map(),
  projectEntries: [],
  equipmentDescriptionOptionMap: new Map(),
  equipmentDescriptionEntries: [],
  equipmentAutocompleteBound: false,
  isSyncingShareTaxCreate: false,
  linkedProjectReturnContext: null,
  equipmentSelectionEventsRegistered: false,
  packageOptionsCache: [],
  createDraftRestoreInProgress: false,
};
