import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

function read(relativePath) {
  return readFileSync(resolve(process.cwd(), relativePath), 'utf8');
}

describe('details page audit', () => {
  it('uses an explicit shared details-page shell for customer and technician pages', () => {
    const customerPage = read('src/pages/customer.html');
    const technicianPage = read('src/pages/technician.html');
    const technicianScript = read('src/scripts/technicianPage.js');
    const techniciansModule = read('src/scripts/technicians.js');
    const tabsShell = read('src/pages/_partials/tabs-manager-shell.html');

    expect(customerPage).toContain('"bodyClass":"details-page customer-page"');
    expect(technicianPage).toContain('"bodyClass":"details-page technician-page"');
    expect(technicianPage).not.toContain('technician-page customer-page');
    expect(tabsShell).toContain('class="btn btn-error btn-sm rounded-full text-error-content dashboard-header-logout-btn"');
    expect(customerPage).toContain('<!-- @include "./_partials/tabs-manager-shell.html"');
    expect(technicianPage).toContain('<!-- @include "./_partials/tabs-manager-shell.html"');
    expect(customerPage).not.toContain('>👤 بيانات العميل<');
    expect(technicianPage).not.toContain('>😎 بيانات عضو الطاقم<');
    expect(technicianPage).not.toContain('data-i18n-key="dashboard.quickLinks.home"');
    expect(technicianPage).toContain('data-i18n-key="tabs.equipment"');
    expect(technicianPage).toContain('data-i18n-key="tabs.maintenance"');
    expect(customerPage).toContain('class="ui-tab tab-button active" href="clients.html"');
    expect(technicianPage).toContain('class="ui-tab tab-button active" href="crew.html"');
    expect(technicianPage).not.toContain('<template data-slot="greetingToggleMeta">');
    expect(technicianPage).not.toContain('dashboard-toggle-technician-status');
    expect(technicianPage).not.toContain('dashboard-toggle-technician-role-badge');
    expect(technicianPage).not.toContain('dashboard-toggle-technician-department');
    expect(technicianPage).toContain('id="technician-hero-status" class="technician-badge" hidden');
    expect(technicianPage).toContain('data-technician-tab-panel="projects" hidden');
    expect(technicianPage).toContain('class="ui-card ui-card--content glass-card dashboard-tabbar detail-tabbar technician-tabbar"');
    expect(technicianPage).toContain('class="modal fade customer-edit-modal technician-edit-modal" id="editTechnicianModal"');
    expect(technicianPage).toContain('class="modal-dialog modal-lg modal-dialog-scrollable customer-edit-modal__dialog"');
    expect(technicianPage).toContain('class="modal-content customer-edit-modal__content technician-edit-modal__content"');
    expect(technicianPage).toContain('class="management-form customer-edit-form technician-edit-form"');
    expect(technicianPage).toContain('class="modal hidden customer-edit-modal technician-financial-modal"');
    expect(technicianPage).toContain('class="modal-dialog modal-lg modal-dialog-scrollable customer-edit-modal__dialog technician-financial-modal__dialog"');
    expect(technicianPage).toContain('class="modal-content customer-edit-modal__content technician-financial-modal__content"');
    expect(technicianPage).toContain('class="modal-header customer-edit-modal__header technician-financial-modal__header"');
    expect(technicianPage).toContain('class="modal-body customer-edit-modal__body technician-financial-modal__body"');
    expect(technicianPage).toContain('class="management-form technician-payout-form technician-financial-modal__payout-form"');
    expect(technicianPage).toContain('class="modal-footer customer-edit-modal__footer technician-financial-modal__footer"');
    expect(technicianPage).not.toContain('data-i18n-key="customerDetails.primaryNav.reservations"');
    expect(technicianPage).not.toContain('data-i18n-key="customerDetails.primaryNav.projects"');
    expect(technicianScript).toContain('element.hidden = !hasValue;');
    expect(technicianScript).toContain('element.hidden = false;');
    expect(technicianScript).toContain('panel.hidden = key !== tab;');
    expect(technicianScript).toContain('function populateTechnicianEditModal(technician)');
    expect(technicianScript).toContain('async function handleTechnicianEditSave()');
    expect(technicianScript).toContain("if (phoneText) infoParts.push(`📞 ${phoneText}`);");
    expect(technicianScript).toContain("if (departmentText) infoParts.push(`🧩 ${departmentText}`);");
    expect(technicianScript).not.toContain("const toggleStatusEl = document.getElementById('dashboard-toggle-technician-status');");
    expect(technicianScript).not.toContain("const toggleRoleBadgeEl = document.getElementById('dashboard-toggle-technician-role-badge');");
    expect(technicianScript).not.toContain("const toggleDepartmentEl = document.getElementById('dashboard-toggle-technician-department');");
    expect(technicianScript).toContain('const targets = [heroStatusEl].filter(Boolean);');
    expect(technicianScript).toContain('function isReservationEligibleForFinancialSummary(reservation, projectsMap = null)');
    expect(technicianScript).toContain('const projectsState = getProjectsState();');
    expect(technicianScript).toContain('const projectsMap = new Map(');
    expect(technicianScript).toContain('const { effectiveConfirmed, projectLinked, projectStatus } = resolveReservationProjectState(reservation, project);');
    expect(technicianScript).toContain("if (isReservationCompleted(reservation) || effectiveStatus === 'completed') {");
    expect(technicianScript).toContain("return ['confirmed', 'مؤكد', 'مؤكدة'].includes(effectiveStatus);");
    expect(technicianScript).toContain("document.addEventListener('projects:changed', handleReservationsUpdated, { passive: true });");
    expect(technicianScript).not.toContain('[data-technician-tab-trigger]');
    expect(technicianScript).not.toContain('technician:prefill');
    expect(technicianScript).not.toContain("panel.classList.toggle('hidden', key !== tab);");
    expect(techniciansModule).toContain("function hasTechniciansModuleDom()");
    expect(techniciansModule).toContain("if (!hasTechniciansModuleDom()) {");
  });

  it('keeps shared detail page dark styling explicit in app.css', () => {
    const appCss = read('src/styles/app.css');
    const technicianPage = read('src/pages/technician.html');

    expect(appCss).toContain('.details-page .form-control');
    expect(appCss).toContain('.details-page .glass-card');
    expect(appCss).toContain('.details-page .bg-primary\\/10');
    expect(appCss).toContain('background-color: rgba(86, 126, 86, 0.22) !important;');
    expect(appCss).toContain('background-color: rgba(154, 170, 145, 0.18) !important;');
    expect(appCss).toContain('background: rgba(20, 30, 24, 0.9);');
    expect(appCss).toContain('background: linear-gradient(135deg, rgba(86, 126, 86, 0.2), rgba(53, 76, 63, 0.24));');
    expect(appCss).toContain('.dashboard-hero-brand');
    expect(appCss).toContain('text-decoration: none;');
    expect(appCss).not.toContain('.details-page .dashboard-header {');
    expect(appCss).toContain('.details-page .glass-card:not(.dashboard-greeting-panel):not(.primary-actions-card)');
    expect(appCss).toContain('.details-page .detail-tabbar .tab-buttons {');
    expect(appCss).toContain('display: grid !important;');
    expect(appCss).toContain('grid-template-columns: repeat(2, max-content) !important;');
    expect(appCss).toContain('width: fit-content !important;');
    expect(appCss).toContain('justify-content: center !important;');
    expect(appCss).toContain('flex-wrap: nowrap !important;');
    expect(appCss).toContain('align-items: stretch;');
    expect(appCss).toContain('padding-block: 0.65rem !important;');
    expect(appCss).toContain('margin: 0 auto !important;');
    expect(appCss).toContain('.details-page .detail-tabbar .tab-button {');
    expect(appCss).toContain('white-space: nowrap;');
    expect(appCss).toContain('width: auto;');
    expect(appCss).toContain('flex: none !important;');
    expect(appCss).toContain("[dir='ltr'] .details-page .detail-tabbar .tab-button,");
    expect(appCss).toContain('@media (max-width: 767px) {');
    expect(appCss).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));');
    expect(appCss).toContain('.details-page .filters-bar {');
    expect(appCss).toContain('.details-page .filters-bar > :first-child {');
    expect(appCss).toContain('width: 100% !important;');
    expect(appCss).toContain('min-width: 0 !important;');
    expect(appCss).toContain('.details-page .detail-tabbar.detail-tabbar--compact .tab-buttons {');
    expect(appCss).toContain('padding-inline: 0.65rem !important;');
    expect(appCss).toContain('.details-page .filters-bar.filters-bar--compact {');
    expect(appCss).toContain('body.details-page:is(.dark, .dark-mode, [data-theme="dark"]) :is(.project-shell-modal, .reservation-shell-modal) .customer-edit-modal__content {');
    expect(appCss).toContain('.technician-financial-modal__dialog {');
    expect(appCss).toContain('.details-page .technician-financial-modal .technician-financial-modal__content {');
    expect(appCss).toContain('linear-gradient(180deg, rgba(24, 36, 29, 0.98), rgba(20, 30, 24, 0.98))');
    expect(appCss).toContain('box-shadow: 0 28px 68px rgba(5, 16, 11, 0.42) !important;');
    expect(appCss).toContain('.details-page .technician-financial-modal .technician-financial-modal__body {');
    expect(appCss).toContain('.details-page .technician-financial-modal .technician-financial-modal__header .btn-close {');
    expect(appCss).toContain('.details-page .technician-financial-modal .technician-financial-modal__payout-form .form-control,');
    expect(appCss).toContain('.details-page .technician-financial-modal .technician-financial-modal__section-hint {');
    expect(appCss).toContain('.technician-financial-modal__summary-card,');
    expect(appCss).toContain('#technician-financial-modal-summary {');
    expect(appCss).toContain('background: rgba(20, 30, 24, 0.74);');
    expect(appCss).toContain('.technician-financial-modal__table-shell {');
    expect(appCss).toContain('.technician-financial-table {');
    expect(appCss).toContain('width: max(100%, 74rem);');
    expect(appCss).toContain('min-width: 74rem;');
    expect(appCss).toContain('scrollbar-gutter: stable both-edges;');
    expect(appCss).toContain('.technician-financial-table thead th {');
    expect(appCss).toContain('.technician-financial-table__primary {');
    expect(appCss).toContain('.technician-financial-table__secondary {');
    expect(appCss).toContain('.technician-financial-table__row > * {');
    expect(appCss).toContain('.technician-financial-modal__close-btn,');
    expect(appCss).toContain('.technician-edit-form .management-form-grid {');
    expect(appCss).toContain('.customer-edit-modal .customer-edit-modal__header .btn-close::before {');
    expect(appCss).not.toContain('.dashboard-greeting-inline-meta {');
    expect(appCss).not.toContain('.technician-page .glass-card,');
    expect(appCss).not.toContain('#technician-financial-modal th,');
    expect(appCss).not.toContain('#technician-financial-modal td {');
    expect(appCss).not.toContain('.technician-work-status-badge {');
    expect(appCss).not.toContain('.technician-payment-badge {');
    expect(technicianPage).toContain('class="users-table-wrapper overflow-x-auto technician-financial-modal__table-shell"');
    expect(technicianPage).toContain('class="ui-table users-table surface-table table table-hover align-middle technician-financial-table"');
    expect(technicianPage).toContain('data-i18n-key="technicianFinancial.list.workStatusColumn"');
  });

  it('keeps technician projects and shared mobile cards on the detail-page base contract', () => {
    const technicianDetailsScript = read('src/scripts/technicianDetails.js');
    const reservationsCss = read('src/styles/reservations.css');
    const coreCss = read('src/styles/core.css');

    expect(technicianDetailsScript).toContain('renderProjectGridEmptyCopy(emptyMessage)');
    expect(technicianDetailsScript).toContain('class="linked-records-empty-copy project-card-grid__empty-line"');
    expect(technicianDetailsScript).not.toContain('<div class="alert alert-info text-center mb-0">${emptyMessage}</div>');
    expect(reservationsCss).toContain('.details-page .customer-reservations-section #customer-reservations > .reservations-grid,');
    expect(reservationsCss).toContain('.details-page .technician-reservations-section #technician-reservations > .reservations-grid {');
    expect(reservationsCss).toContain('display: grid;');
    expect(reservationsCss).toContain('grid-template-columns: 1fr;');
    expect(reservationsCss).toContain('.details-page .customer-reservations-section .tile-row,');
    expect(reservationsCss).toContain('.details-page .technician-reservations-section .tile-row {');
    expect(reservationsCss).toContain('flex-direction: column;');
    expect(coreCss).toContain('.projects-page .project-focus-card,');
    expect(coreCss).toContain('.details-page .project-focus-card {');
    expect(coreCss).not.toContain('.details-page .project-focus-card__actions > * {');
  });

  it('keeps technician financial modal english copy explicit for placeholder and runtime fallbacks', () => {
    const technicianTranslations = read('src/scripts/translations/technician.js');
    const technicianPageScript = read('src/scripts/technicianPage.js');
    const fixtureScript = read('src/scripts/devFixtures.js');

    expect(technicianTranslations).toContain("'technicianFinancial.payouts.form.notePlaceholder': 'Example: quick payout or transfer reference'");
    expect(technicianTranslations).toContain("'technicianFinancial.fixturePayout.day1': 'دفعة اليوم الأول'");
    expect(technicianTranslations).toContain("'technicianFinancial.fixturePayout.day1': 'Day 1 payout'");
    expect(technicianTranslations).toContain("'technicianFinancial.list.workStatus.completed': 'مغلق'");
    expect(technicianTranslations).toContain("'technicianFinancial.list.workStatus.completed': 'Closed'");
    expect(technicianTranslations).toContain("'technicianFinancial.list.workStatusColumn': 'حالة الحجز'");
    expect(technicianTranslations).toContain("'technicianFinancial.list.workStatusColumn': 'Reservation status'");
    expect(technicianPageScript).toContain("t('technicianFinancial.stats.totalDesc', 'Across {count} assignments')");
    expect(technicianPageScript).toContain("t('technicianFinancial.stats.paidDesc', '{count} payouts recorded')");
    expect(technicianPageScript).toContain("t('technicianFinancial.stats.outstandingDesc', 'Outstanding {amount}')");
    expect(technicianPageScript).toContain("t('technicianFinancial.list.settled', 'None')");
    expect(technicianPageScript).toContain("t('technicianFinancial.payouts.toast.failed', '⚠️ Unable to record the payout. Please try again.')");
    expect(technicianPageScript).toContain("function resolveFinancialWorkStatusLabel(status)");
    expect(technicianPageScript).toContain("function buildFinancialWorkStatusBadge(status)");
    expect(technicianPageScript).toContain("function resolvePayoutNoteText(entry = {})");
    expect(technicianPageScript).toContain("let badgeClass = 'reservation-chip status-chip status-unpaid';");
    expect(technicianPageScript).toContain("badgeClass = 'reservation-chip status-chip status-paid';");
    expect(technicianPageScript).toContain("badgeClass = 'reservation-chip status-chip status-partial';");
    expect(technicianPageScript).toContain('class="reservation-chip status-chip ${statusClass}"');
    expect(technicianPageScript).toContain('class="technician-financial-table__primary"');
    expect(technicianPageScript).toContain('class="technician-financial-table__secondary"');
    expect(technicianPageScript).toContain('class="technician-financial-table__cell technician-financial-table__cell--work-status"');
    expect(technicianPageScript).not.toContain('technician-work-status-badge');
    expect(technicianPageScript).not.toContain('technician-payment-badge');
    expect(technicianPageScript).not.toContain("referenceParts.push(`#${normalizeNumbers(String(refId))}`);");
    expect(fixtureScript).toContain("note_key: 'technicianFinancial.fixturePayout.day1'");
  });

  it('keeps shared detail surfaces on the refined dark contract without policing reservation card palette', () => {
    const coreCss = read('src/styles/core.css');

    expect(coreCss).toContain('background: rgba(20, 30, 24, 0.72);');
    expect(coreCss).toContain('border-color: rgba(147, 168, 137, 0.24);');
    expect(coreCss).toContain('color: rgba(201, 214, 196, 0.9);');
    expect(coreCss).toContain('background: rgba(22, 28, 25, 0.94);');
    expect(coreCss).toContain('background: rgba(86, 126, 86, 0.18);');
    expect(coreCss).not.toContain('background: rgba(15, 23, 42, 0.7);');
    expect(coreCss).not.toContain('border-color: rgba(96, 165, 250, 0.25);');
  });
});
